### ISSUE TITLE
would like to link to this module

### ISSUE THREAD

**Issue by grawk** [aredridel/put-packages-in-requirejs-config#1]
Writing up some documentation on makara/dust compilation in the browser and intend to link to this module's README. Currently there are no branches, so a link to the repo just brings up a message to that effect

**Comment by aredridel** [comment]
Oh goodness! I'll fix that :)

**Comment by aredridel** [comment]
Fixed! That was very weird -- tags but no branches, I suspect github actually broke something in this repo.
